/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedColumnsRouteImport } from './routes/_authenticated/columns'
import { Route as AuthenticatedFlightsRouteImport } from './routes/_authenticated/flights'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedManualTransfersRouteImport } from './routes/_authenticated/manual-transfers'
import { Route as AuthenticatedManualTransfersProRouteImport } from './routes/_authenticated/manual-transfers-pro'
import { Route as AuthenticatedPagesRouteImport } from './routes/_authenticated/pages'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedTransfersProRouteImport } from './routes/_authenticated/transfers-pro'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVisasRouteImport } from './routes/_authenticated/visas'
import { Route as AuthenticatedWorkersRouteImport } from './routes/_authenticated/workers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedColumnsRoute = AuthenticatedColumnsRouteImport.update({
  id: '/columns',
  path: '/columns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlightsRoute = AuthenticatedFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManualTransfersRoute =
  AuthenticatedManualTransfersRouteImport.update({
    id: '/manual-transfers',
    path: '/manual-transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManualTransfersProRoute =
  AuthenticatedManualTransfersProRouteImport.update({
    id: '/manual-transfers-pro',
    path: '/manual-transfers-pro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagesRoute = AuthenticatedPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersProRoute =
  AuthenticatedTransfersProRouteImport.update({
    id: '/transfers-pro',
    path: '/transfers-pro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisasRoute = AuthenticatedVisasRouteImport.update({
  id: '/visas',
  path: '/visas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkersRoute = AuthenticatedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/columns': typeof AuthenticatedColumnsRoute
  '/flights': typeof AuthenticatedFlightsRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/manual-transfers': typeof AuthenticatedManualTransfersRoute
  '/manual-transfers-pro': typeof AuthenticatedManualTransfersProRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/transfers-pro': typeof AuthenticatedTransfersProRoute
  '/users': typeof AuthenticatedUsersRoute
  '/visas': typeof AuthenticatedVisasRoute
  '/workers': typeof AuthenticatedWorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/columns': typeof AuthenticatedColumnsRoute
  '/flights': typeof AuthenticatedFlightsRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/manual-transfers': typeof AuthenticatedManualTransfersRoute
  '/manual-transfers-pro': typeof AuthenticatedManualTransfersProRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/transfers-pro': typeof AuthenticatedTransfersProRoute
  '/users': typeof AuthenticatedUsersRoute
  '/visas': typeof AuthenticatedVisasRoute
  '/workers': typeof AuthenticatedWorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/columns': typeof AuthenticatedColumnsRoute
  '/_authenticated/flights': typeof AuthenticatedFlightsRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRoute
  '/_authenticated/manual-transfers': typeof AuthenticatedManualTransfersRoute
  '/_authenticated/manual-transfers-pro': typeof AuthenticatedManualTransfersProRoute
  '/_authenticated/pages': typeof AuthenticatedPagesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/transfers-pro': typeof AuthenticatedTransfersProRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/visas': typeof AuthenticatedVisasRoute
  '/_authenticated/workers': typeof AuthenticatedWorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/columns'
    | '/flights'
    | '/forms'
    | '/manual-transfers'
    | '/manual-transfers-pro'
    | '/pages'
    | '/reports'
    | '/requests'
    | '/security'
    | '/transfers'
    | '/transfers-pro'
    | '/users'
    | '/visas'
    | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/columns'
    | '/flights'
    | '/forms'
    | '/manual-transfers'
    | '/manual-transfers-pro'
    | '/pages'
    | '/reports'
    | '/requests'
    | '/security'
    | '/transfers'
    | '/transfers-pro'
    | '/users'
    | '/visas'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/columns'
    | '/_authenticated/flights'
    | '/_authenticated/forms'
    | '/_authenticated/manual-transfers'
    | '/_authenticated/manual-transfers-pro'
    | '/_authenticated/pages'
    | '/_authenticated/reports'
    | '/_authenticated/requests'
    | '/_authenticated/security'
    | '/_authenticated/transfers'
    | '/_authenticated/transfers-pro'
    | '/_authenticated/users'
    | '/_authenticated/visas'
    | '/_authenticated/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/columns': {
      id: '/_authenticated/columns'
      path: '/columns'
      fullPath: '/columns'
      preLoaderRoute: typeof AuthenticatedColumnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flights': {
      id: '/_authenticated/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AuthenticatedFlightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manual-transfers': {
      id: '/_authenticated/manual-transfers'
      path: '/manual-transfers'
      fullPath: '/manual-transfers'
      preLoaderRoute: typeof AuthenticatedManualTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manual-transfers-pro': {
      id: '/_authenticated/manual-transfers-pro'
      path: '/manual-transfers-pro'
      fullPath: '/manual-transfers-pro'
      preLoaderRoute: typeof AuthenticatedManualTransfersProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pages': {
      id: '/_authenticated/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AuthenticatedPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers-pro': {
      id: '/_authenticated/transfers-pro'
      path: '/transfers-pro'
      fullPath: '/transfers-pro'
      preLoaderRoute: typeof AuthenticatedTransfersProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visas': {
      id: '/_authenticated/visas'
      path: '/visas'
      fullPath: '/visas'
      preLoaderRoute: typeof AuthenticatedVisasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers': {
      id: '/_authenticated/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthenticatedWorkersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedColumnsRoute: typeof AuthenticatedColumnsRoute
  AuthenticatedFlightsRoute: typeof AuthenticatedFlightsRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedManualTransfersRoute: typeof AuthenticatedManualTransfersRoute
  AuthenticatedManualTransfersProRoute: typeof AuthenticatedManualTransfersProRoute
  AuthenticatedPagesRoute: typeof AuthenticatedPagesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedTransfersProRoute: typeof AuthenticatedTransfersProRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVisasRoute: typeof AuthenticatedVisasRoute
  AuthenticatedWorkersRoute: typeof AuthenticatedWorkersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedColumnsRoute: AuthenticatedColumnsRoute,
  AuthenticatedFlightsRoute: AuthenticatedFlightsRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedManualTransfersRoute: AuthenticatedManualTransfersRoute,
  AuthenticatedManualTransfersProRoute: AuthenticatedManualTransfersProRoute,
  AuthenticatedPagesRoute: AuthenticatedPagesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedTransfersProRoute: AuthenticatedTransfersProRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVisasRoute: AuthenticatedVisasRoute,
  AuthenticatedWorkersRoute: AuthenticatedWorkersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
